### ISSUE TITLE
Javascript and 405 error

### ISSUE THREAD

**Issue by codecleric** [wshallum/couchadaptor#18]
The project isn't working for me against a CouchDB Server (1.6.1) I control, that isn't behind another web server. I have observed two issues:

1. The basic Wiki display correctly,  but the console shows an error:

> Failed to load resource: The server responded with a status of 405.

2. When I try to create a new tiddler, an error dialog comes up:

> Uncaught TypeError: this.syncadaptor.isReady is not a function

The tiddler is created in browser, but is not saved in the DB.

I double checked the instructions and the build and publish parts have gone without a problem.

Thanks!

**Comment by codecleric** [comment]
Well, I see that my version of TiddlyWiki (From the TiddlyWiki install instructions) is version 5.1.12, but you require 5.1.2 or greater. I'll figure out how to get that one...

**Comment by danielo515** [comment]
The plugin needs a fix. @Jermolene introduced a new feature in the latest release that breaks backwards compatibility with all the sync adapters. He was trying to fix a problem, but has broke all the sync adapters

**Comment by wshallum** [comment]
Hi @danielo515, thanks for the info. I will look into updating it on the weekend. I believe this is the breaking change: https://github.com/Jermolene/TiddlyWiki5/commit/c3d18364c1b52cf89c1281b440d49f7df0d3a89a ?

**Comment by Jermolene** [comment]
Hi @wshallum @danielo515 the underlying problem is fixed for 5.1.14 in 7326a3a4ccf552c5eb54682f48b3e108c9f4afd4
