### ISSUE TITLE
Single File instructions

### ISSUE THREAD

**Issue by danielo515** [wshallum/couchadaptor#3]
Hello.

I tried to follow the instructions to setup the plugin for using it with the single file edition with no luck. I edited the file config.multids with the url of my couch db instance. It is not happening anything! It is not triggering any communication with the server. The configuration seems to be ok. I provided also the document and the ask for credentials. I tried to follow the procedure to upload the index as an app to the database and it works perfectly. What I'm doing wrong? I feel very close but I'm missing something.

**Comment by wshallum** [comment]
Hi Daniel,

Can you give more information:

* What are the contents of your config.multids file?
* Where did you put the generated index.html (what URL did you use to access it)?
* Does your CouchDB server require authentication for getting / updating data? Have you configured CORS on your CouchDB server?
* What version of TiddlyWiki are you using? It is possible that something changed as this has not been touched in quite some time. If you give me a version I can try to reproduce the issue.

Thanks,
William

**Comment by danielo515** [comment]
Hello Wshallum,

Thank you for answering.
Here is the information

* This is the content of my multids file

> Url: https://danielo515.cloudant.com/tw
DesignDocumentName: tw
RequiresWithCredentials: yes

* I'm trying to run the file locally, as a file. So the URL is file://C:/route/to/index.html
* Yes my server accepts CORS. I'm using cloudant as provider. If CORS is not allowed I would expect some errors on the console and some network calls, but none of those things are happening.
* I'm using TW 5.1.8. I don't think is a problem with tw version because, as I said, it does work with the version uploaded as a document. Even with the multids parameters unchanged.

**Comment by danielo515** [comment]
I think I found the problem.

At the end of the adaptor you can see

```
if($tw.browser && document.location.protocol.substr(0,4) === "http"
```
if you remove the second part it works perfectly. Some problems with the storyList synchronization, but that's all. Why have you added such constraint?

**Comment by wshallum** [comment]
Looks like you found the problem! I think I added that so it will not interfere with file based wikis saving to local files.

**Comment by wshallum** [comment]
And also it was in the original tiddlyweb sync adaptor: https://github.com/Jermolene/TiddlyWiki5/blob/v5.1.8/plugins/tiddlywiki/tiddlyweb/tiddlywebadaptor.js#L312 so I just followed that :)

**Comment by danielo515** [comment]
Ok, I see the reason.

It makes sense because you can have scenarios where saving is not possible on single file because you are offline. I think a better "check" should be added, like for example if the server is reachable or the username and password is correct

**Comment by wshallum** [comment]
I'm not sure that's possible given the way that TW5 loads sync adaptors once at startup. See: https://github.com/Jermolene/TiddlyWiki5/blob/1e02df61d0e3ec4158536376c0888f4d589b41be/core/modules/startup/startup.js#L66

Blocking startup to run a synchronous check of a server that may not be reachable doesn't sound like a good idea. 

At this point it is probably safe to say that the current version of this adaptor is really meant to run as a CouchApp (from the same server). The fact that it is possible to put the file on a separate HTTP server is just a nice bonus.

**Comment by wshallum** [comment]
Is there anything left to do on this issue or can this be closed now?

**Comment by danielo515** [comment]
Since it is not documented in any place I think we should instruct how to activate the single file sync. Just a statement on the readme would be enough. I have ideas to add an extra condition to the sync adaptor to decide if it is able to sync or not, and may be related with this. Basically only since if the url tiddler has text. 

Regards
