### ISSUE TITLE
Only titles is not enough as skinny

### ISSUE THREAD

**Issue by danielo515** [wshallum/couchadaptor#5]
Normally skinny tiddlers are all tiddler fields except the text field. Since this is too much from my point of view (many times, we use other fields that are larger than the text field) we have to include at least, the modification date and tags. This way you can search tiddlers by tags and you can see a list of recent tiddlers.

I tried to modify the _skinny tiddlers view myself, but I have failed. If you guide it me a bit I can try to do it myself.

**Comment by wshallum** [comment]
Hi Daniel,

The docs for view functions are here: http://docs.couchdb.org/en/latest/couchapp/ddocs.html#view-functions

So you can probably just change it to 

    emit(doc._id, {rev: doc._rev, otherfield: doc.fields.otherfield});

and then modify `CouchAdaptor.prototype.convertFromSkinnyTiddler` to 

    return {title: this.demangleTitle(row.key), revision: row.value.rev, otherfield: row.value.otherfield};

**Comment by danielo515** [comment]
Hello @wshallum 

I was thinking in something similar to what you said. I ended up with a working solution very satisfying thanks to your advise. Maybe I can made another pull request. 

I have a doubt regarding this that I think is very important. I think I have the correct view configured because I have uploaded the wiki file as a document, and it has created them. Is this correct? Or maybe the plugin creates this views in some magical way? If so, I have to edit the view templates also. Regards

**Comment by wshallum** [comment]
Hi Daniel,

There is no magic view-creation going on in the plugin itself. The view is created on the CouchDB server when the couchapp is pushed (`bin/push.sh`). If you upload the wiki that way then yes, the view will be updated from the definition inside `couchapp.js`.

If you want to make a pull request I suggest you change both the view definition in the `couchapp.js` file and the `convertFromSkinnyTiddler` function in `couchdbadaptor.js`.

**Comment by danielo515** [comment]
Hello @wshallum 

I ended deducting what you have explained. Thank you very much. I have just updated the couchapp.js (it was the only thing left). I have Updated the `convertFromSkinnyTiddler` function already. So now I'm ready for another pull request. What I have changed, basically, is that now the convertFromSkinnyTiddler function does not have "hardcoded" the fields that it has to convert. The view returns an object in the value field of the response that contains all the fields that are supposed to be part of the skinny definition except the title, which is injected by the convert function. What do you think about that?


Regarding the "view" creation, would you consider to include the view creation in the plugin itself? Or maybe create a disposable plugin just for this purpose? That plugin could create the needed "configuration tiddlers" through an easy GUI. Then the couch-db plugin should check if the needed configuration tiddlers exists and only "act" if those configuration tiddlers are set. That will make things definitively easier for newcomers

**Comment by wshallum** [comment]
> The view returns an object in the value field of the response that contains all the fields that are supposed to be part of the skinny definition except the title, which is injected by the convert function. What do you think about that?

Sure, that would be nicer.

> Regarding the "view" creation, would you consider to include the view creation in the plugin itself?

I'm not sure why you want something like this. The way I see it is:

* The user has to have tiddlywiki from npm before using this adaptor (required to build HTML)
* ...so having the user install couchapp from npm is not much of an additional burden
* ...then the user sets up the username, password, and URL for push
* ...and it all just works

Am I correct in assuming that you want a single HTML file that you can point to random CouchDB servers? I'm not sure that works as currently you have to modify the CouchDB URL in the generated HTML file. If you have to do that anyway, running another push to update the views is not really a problem.

> That plugin could create the needed "configuration tiddlers" through an easy GUI. Then the couch-db plugin should check if the needed configuration tiddlers exists and only "act" if those configuration tiddlers are set.

Where would these configuration tiddlers (e.g. database URL) be stored? Obviously not in CouchDB (chicken and egg problem). Local storage?

**Comment by danielo515** [comment]
> I'm not sure that works as currently you have to modify the CouchDB URL in the generated HTML file.

That is one point I want to discuss with you. Since the couch URL is a tiddler, ad your plugin just reads that tiddler, there is no need to rebuild the entire file. Just reloading the page would be enough. I think the current work flow does it because at the end, the build and the push are mandatory steps for configuring the server,but once the server is configured there is no need to rebuild and push, just change the url or the document or the database.

**Comment by wshallum** [comment]
OK, can you comment on issue #6 instead? Let's make #5 only about the skinny tiddler view.

**Comment by danielo515** [comment]
Fixed in 6a7a13c
