### ISSUE TITLE
Provide an option to ignore connectivity issues? 

### ISSUE THREAD

**Issue by danielo515** [wshallum/couchadaptor#8]
Hello. 

It's very annoying to get an alert every 30 seconds because you have just turn of wifi at have disconnected the wire. Maybe we can provide an option to disable notifications for errors related to connectivity?

**Comment by wshallum** [comment]
Can you please check how other sync adaptors (e.g. the tiddlyweb one) handle broken connections? It's not like the notifications are coming from the sync adaptor. It is just reporting errors back to the TW core. Maybe TW core can throttle back the calls to getSkinnyTiddlers if it detects repeated errors.

**Comment by danielo515** [comment]
Hello, 

You are right and I was aware of it. In fact I have opened a ticket to TW main repo for a less annoying notification system. I just thought that maybe we can have a workaround meanwhile.

**Comment by wshallum** [comment]
Closing. Not my problem :)
