### ISSUE TITLE
Public read only databases

### ISSUE THREAD

**Issue by danielo515** [wshallum/couchadaptor#9]
Hello.

One use case of this plugin could be a BLOG. How? Whit a database that is publicly available only for read. We can have  an HTML file without any editing capabilities, but it reads its tiddlers from the database. Then we can have another normal TW that does have editing capabilities and we log into it as an authorized user with write permissions to the database. 

This is very easy to accomplish with cloudant, for example but I'm not sure if this is a feature of couchdb. As far as I know, you have to configure a document with the appropriate view for this kind of management in any other couchdb platform. May you can throw some light on this.

**Comment by wshallum** [comment]
I think this already works. Try it using a local CouchDB (with an admin added, not in admin party mode) and see. By default the [validate_doc_update](http://docs.couchdb.org/en/1.6.1/couchapp/ddocs.html#validate-document-update-functions) in `couchapp.js` will deny write requests from unauthenticated users. The missing piece is just disabling edit controls.

**Comment by danielo515** [comment]
You are talking about this right?

```
function (newDoc, oldDoc, userCtx) {
	if (userCtx.name === null) {
		/* check if the unnamed user has _admin role (admin party mode) */
		if (userCtx.roles.length > 0 && userCtx.roles[0] === "_admin") {
			return;
		}
		throw({unauthorized: "Please log in"});
	}
}
```

This is inside the design view of TW. Is it created by default or is it created by your scripts (couchapp.js) ?

**Comment by danielo515** [comment]
Yes, it is created by your couchapp.js. Then this is already done! Can this be extended to have public and private tiddlers?

**Comment by wshallum** [comment]
Not sure there's a function for that (per document read validation). All documents are readable to members: http://couchdb.readthedocs.org/en/1.6.1/api/database/security.html

**Comment by danielo515** [comment]
That seems to be a limitation of couchdb. You can not have a public read database if you create any user. You have to decide to only  have admin users or make your database totally private.

**Comment by wshallum** [comment]
OK, the conclusion is. 

* Public read-only: possible and already working
* Private tiddlers: not possible without a lot of tricks in the DB (filtered replication?): https://wiki.apache.org/couchdb/PerDocumentAuthorization

Closing issue now.
